class Solution {
public:
    char findKthBit(int n, int k) {
        if (n == 1) {
            return '0';
        }
        int len = (1 << n) - 1;
        int mid = (len >> 1) + 1;
        if (k == mid) {
            return '1';
        } else if (k < mid) {
            return findKthBit(n - 1, k);
        } else {
            int mirroredK = len - k + 1;
            char mirroredBit = findKthBit(n - 1, mirroredK);
            return (mirroredBit == '0') ? '1' : '0';
        }
    }
};


/*
LeetCode 1545. Find Kth Bit in Nth Binary String
Given two positive integers n and k, the binary string Sn is formed as follows:
    S1 = "0"
    Si = Si-1 + "1" + reverse(invert(Si-1)) for i > 1
Where + denotes the concatenation operation, reverse(x) returns the reversed string x, and invert(x) inverts all the bits in x (0 changes to 1 and 1 changes to 0).
For example, the first four strings in the above sequence are:
    S1 = "0"
    S2 = "011"
    S3 = "0111001"
    S4 = "011100110110001"
Return the kth bit in Sn. It is guaranteed that k is valid for the given n.

Intuition:
    The function findKthBit(n, k) returns the kth bit in the nth row of the binary string sequence.
    The sequence is generated by appending '1' to the (n-1)th row, then reversing the (n-1)th row and appending '0' to it.
    The function uses a recursive approach to find the kth bit.

Approach:
    1. If n is 1, return '0'.
    2. Calculate the length of the nth row as len = (1 << n) - 1.
    3. Calculate the middle index of the nth row as mid = (len >> 1) + 1.
    4. If k is equal to mid, return '1'.
    The function findKthBit(n, k) returns the kth bit in the nth row of the binary string sequence. 
    5. If k is less than mid, recursively call findKthBit(n - 1, k).
    6. If k is greater than mid, find the mirrored index mirroredK = len - k + 1.
    7. Recursively call findKthBit(n - 1, mirroredK) to find the mirrored bit.
    8. Invert the mirrored bit (if it is '0', return '1', and if it is '1', return '0').
    9. Return the inverted bit.

    Code Explanation:
    step 1: If n is 1, return '0'.
    step 2: Calculate the length of the nth row as len = (1 << n) - 1.
    step 3: Calculate the middle index of the nth row as mid = (len >> 1) + 1.
    step 4: If k is equal to mid, return '1'.
    step 5: If k is less than mid, recursively call findKthBit(n - 1, k).
    step 6: If k is greater than mid, find the mirrored index mirroredK = len - k + 1.
    step 7: Recursively call findKthBit(n - 1, mirroredK) to find the mirrored bit.
    step 8: Invert the mirrored bit (if it is '0', return '1', and if it is '1', return '0').
    step 9: Return the inverted bit.
    
    Complexity :
    Time Complexity: O(n)
    Space Complexity: O(n)
*/
